package constants

const (
	BAD_CREDENTIALS = "BAD_CREDENTIALS"
	TOKEN_EXPIRED   = "TOKEN_EXPIRED"
	INVALID_DATA    = "INVALID_DATA"
	NOT_FOUND       = "NOT_FOUND"
	UNAUTHORIZED    = "UNAUTHORIZED"
)
